# Generated by Django 5.2.9 on 2025-12-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rizhiyi_id",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="日志易用户ID"
                    ),
                ),
                (
                    "rizhiyi_username",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="日志易用户名",
                    ),
                ),
                (
                    "api_key",
                    models.TextField(
                        blank=True, null=True, verbose_name="日志易 API Key"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "用户配置",
                "verbose_name_plural": "用户配置",
            },
        ),
    ]
